package com.cs151.hw1;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CS151_HW1
//  @ File Name : Customer.java
//  @ Date : 9/8/2011
//  @ Author : 
//
//




/** */
public class Customer implements Serializable{
	/** */
	public String name;
	public Customer()
	{
		this.name = "Empty";
	}
	public void setName(String s)
	{
		name = s;
	}
	public void clear()
	{
		this.name = "Empty";
	}
}
